#!/bin/sh

cmd="${1}"
shift
case "${cmd}" in
  build|b) cabal build;;
  repl|r) cabal repl;;
  test:all|t) cabal test --test-show-details=always --test-options="--color always $@";;
  test:pattern|tp) cabal test --test-show-details=always --test-options='--color always -p \"$@\"';;
  exec) cabal run poi -- $@;;
  poi)
    can="${HOME}/test-poi-can"
    [[ ! -d ${can} ]] && mkdir "${can}"
    cabal_flag=""
    if [[ "${TUI_DEBUG}" ]]; then
      cabal_flag="${cabal_flag} -f tui_debug"
    fi
    POI_TRASH_CAN_PATH="${can}" cabal run ${cabal_flag} poi -- $@
    ;;
  versioning|v) sh scripts/versioning;;
  release) sh scripts/release;;
  *) eval "${cmd} $@";;
esac
