#!/bin/sh
function prepare_can
{
  refresh="$1"
  can="${HOME}/test-poi-can"
  [[ -d ${can} ]] && [[ "${refresh}" == 'y' ]] && /bin/rm -rf "${can}"
  [[ ! -d ${can} ]] && mkdir "${can}"
  echo "${can}"
}

function gendata
{
  refresh="$1"
  can="$(prepare_can ${refresh})"
  datasize="$2"
  POI_TRASH_CAN_PATH="${can}" POI_GENDATA_SIZE="${datasize}" cabal run gendata
}

cmd="${1}"
shift
case "${cmd}" in
  build|b) cabal build;;
  repl|r) cabal repl;;
  test:all|t) cabal test --test-show-details=always --test-options="--color always $@";;
  test:pattern|tp) cabal test --test-show-details=always --test-options='--color always -p \"$@\"';;
  exec) cabal run poi -- $@;;
  poi)
    can="$(prepare_can)"
    cabal_flag=""
    if [[ "${TUI_DEBUG}" ]]; then
      cabal_flag="${cabal_flag} -f tui_debug"
    fi
    POI_TRASH_CAN_PATH="${can}" cabal run ${cabal_flag} poi -- $@
    ;;
  versioning|v) sh scripts/versioning;;
  release) sh scripts/release;;
  gendata) gendata ${POI_GENDATA_SIZE:-};;
  gendata-x) gendata 'y' ${POI_GENDATA_SIZE:-};;
  *) eval "${cmd} $@";;
esac
