[tools]
ghcup = "latest"

[tasks.build]
run = "cabal build"
alias = "b"

[tasks."test:all"]
run = "cabal test --test-show-details=always --test-options='--color always {{arg()}}'"
alias = "t"

[tasks."test:pattern"]
run = "cabal test --test-show-details=always --test-options='--color always -p \"{{arg()}}\"'"
alias = "tp"

[tasks.exec]
run = "cabal run poi --"
alias = "x"

[tasks.poi]
run = "echo cabal run poi"
env = { TRASH_CAN_PATH="{{ exec(command='pwd') }}/test-poi-can" }

[tasks.versioning]
run = "sh scripts/versioning"
alias = "v"

[tasks.release]
run = "sh scripts/release"
alias = "r"
