#!/bin/sh

function current_version()
{
  rg '^version:\s*\d+\.\d+\.\d+$' ./poi.cabal | cut -d ':' -f 2 | xargs echo -n
}

version="$(current_version)"
major="$(echo ${version} | cut -d '.' -f 1)"
minor="$(echo ${version} | cut -d '.' -f 2)"
micro="$(echo ${version} | cut -d '.' -f 3)"

cat <<EOF > ./src/Poi/Version.hs
module Poi.Version (version, Version) where

import Data.List (intercalate)

data Version = Version
  { major :: Int
  , minor :: Int
  , micro :: Int
  }
  deriving (Eq)

instance Show Version where
  show (Version{major = x, minor = y, micro = z}) = intercalate "." $ map show [x, y, z]

version :: Version
version = Version ${major} ${minor} ${micro}
EOF
